#!/bin/sh
while read -r f; do
  fp="$PWD/$f"
  case "$1" in
    "d" )
      [ "$(printf "No\\nYes" | dmenu -i -p "Really delete $f?")" = "Yes" ] && rm "$f" && notify-send -u low "sxiv" "Deleted $fp"
      ;;
  esac
done
